[package]
name = "acm-coffee"
version = "0.1.0"
authors = ["Jeffrey McAteer <jeffrey.p.mcateer@gmail.com>"]


[dependencies]
tiny_http = "0.5"
lazy_static = "1.0"
#memmap = "0.6.2"
#libc = "0.2.40"
#mmap = "0.1.1"
image = "*"

